### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Locked15**

### CODE REVIEW

**Comment by Locked15** [comment]
You want it?
You merge it.

**Comment by Locked15** [comment]
Still waiting...

**Comment by Locked15** [comment]
Storm that is approaching...

**Comment by Locked15** [comment]
Provoking black clouds in isolation,...

**Comment by Locked15** [comment]
I am reclaimer of my name...

**Comment by Locked15** [comment]
Born in flames, I have been blessed
My family crest is a demon of death
Forsakened, I am awakened
A phoenix's ash in dark divine
Descending misery
Destiny chasing time.

Merge it.

**Comment by One-StepAhead** [comment]
good joob bro

**Pull request merged**
